services:
  mercadata:
    build: .
    container_name: mercadata_app
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-3000}
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proxy:
    external: true
