version: '3.8'
services:
  web:
    build: .
    tty: true
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: yarn serve
    expose:
      - 8080
