name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main  # O reemplaza con tu rama principal (master, develop, etc.)
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  deploy:
    name: Deploy App
    runs-on: self-hosted  # Usa el runner auto-hospedado
    environment: Production
    env:
      VIRTUAL_HOST: ${{ vars.VIRTUAL_HOST }}
      VIRTUAL_PORT: ${{ vars.VIRTUAL_PORT }}
      VITE_AUTHIFY_URL: ${{ vars.VITE_AUTHIFY_URL }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # git pull origin main
      - name: Build and start containers
        run: |
          echo "Building and starting Docker containers..."
          docker compose down
          docker compose build --no-cache
          docker compose up -d

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          docker compose ps
          echo "Deployment completed successfully!"
